const WORKER = "https://cplex-watcher.cplexwatcher.workers.dev";
const TOKEN_KEY = "UI_ACCESS_TOKEN";
const app = document.querySelector("#app"), groups = document.querySelector("#date-groups"), loadStatus = document.querySelector("#load-status"), actionResult = document.querySelector("#action-result"), dialog = document.querySelector("#watch-dialog"), form = document.querySelector("#watch-form"), formResult = document.querySelector("#form-result");
const DEFAULT_RULE = "E9-E17, F14-F23, G14-G23, H14-H23, I14-I23";
let watches = {}, state = {}, editingWatchId = "";
const token = () => localStorage.getItem(TOKEN_KEY) || "";
const preview = (theatreId, showtimeId) => `https://www.cineplex.com/ticketing/preview?theatreId=${encodeURIComponent(theatreId)}&showtimeId=${encodeURIComponent(showtimeId)}`;
function nextCheck() { const now = new Date(), next = new Date(now); next.setUTCSeconds(0, 0); next.setUTCMinutes(now.getUTCMinutes() < 30 ? 30 : 60); return Math.max(1, Math.ceil((next - now) / 60_000)); }
function login() { window.location.replace("./login.html"); }
async function request(path, method, body) { const response = await fetch(`${WORKER}${path}`, { method, headers: { "content-type": "application/json", authorization: `Bearer ${token()}` }, body: body ? JSON.stringify(body) : undefined }); const value = await response.json(); if (!response.ok) { if (response.status === 401) { localStorage.removeItem(TOKEN_KEY); login(); } throw new Error(value.error || "Request failed."); } return value; }
function parseRule(value) { const rule = {}; for (const range of value.split(",")) { const match = /^\s*([a-z]+)(\d+)\s*-\s*([a-z]+)(\d+)\s*$/i.exec(range); if (!match || match[1].toUpperCase() !== match[3].toUpperCase()) throw new Error("Seat labels must look like E9-E17."); const start = Number(match[2]), end = Number(match[4]); if (!start || start > end) throw new Error("Seat ranges must be positive and ascending."); (rule[match[1].toUpperCase()] ||= []).push([start, end]); } if (!Object.keys(rule).length) throw new Error("Provide at least one seat range."); return rule; }
function ruleText(rule) { return Object.entries(rule || {}).flatMap(([row, ranges]) => ranges.map(([start, end]) => `${row}${start}-${row}${end}`)).join(", "); }
function date(value) { const parsed = new Date(value); return Number.isNaN(parsed) ? "Unknown date" : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", weekday: "long", month: "short", day: "numeric" }).format(parsed); }
function items() { return Object.values(watches).filter((watch) => watch.enabled).flatMap((watch) => Object.entries(watch.showtimes || {}).filter(([, showtime]) => showtime.enabled).map(([id, showtime]) => ({ watch, id, showtime, check: state[watch.id]?.showtimes?.[id] || {} }))).sort((a, b) => String(a.showtime.startsAt || "").localeCompare(String(b.showtime.startsAt || ""))); }
function openForm(watch = null) { editingWatchId = watch?.id || ""; form.reset(); formResult.textContent = ""; document.querySelector("#watch-dialog-title").textContent = watch ? `Edit ${watch.name}` : "Add seat watcher"; document.querySelector("#watch-dialog-hint").textContent = watch ? "Saving rechecks every showtime and starts a fresh seat scan." : "Use a name and showtime IDs. Date and time are found automatically."; document.querySelector("#save-watch").textContent = watch ? "Save changes" : "Start watching"; document.querySelector("#watch-name").value = watch?.name || ""; document.querySelector("#theatre-id").value = watch?.theatreId || ""; document.querySelector("#theatre-name").value = watch?.theatreName || ""; document.querySelector("#showtime-ids").value = watch ? Object.keys(watch.showtimes || {}).join(", ") : ""; document.querySelector("#seat-rule").value = watch ? ruleText(watch.rule) : DEFAULT_RULE; dialog.showModal(); }
function availableCount(item) { return Object.values(item.check.selectedSeats || {}).filter((seat) => seat.status === "Available").length; }
function stopShowtimeButton(item) { const stop = document.createElement("button"); stop.className = "stop"; stop.type = "button"; stop.textContent = "Stop"; stop.onclick = async () => { if (!confirm(`Stop #${item.id} for ${item.watch.name}?`)) return; stop.disabled = true; try { await request(`/api/seat-watches/${encodeURIComponent(item.watch.id)}/showtimes/${item.id}`, "DELETE"); actionResult.textContent = "Stop request queued. Refresh shortly."; } catch (error) { actionResult.textContent = error.message; stop.disabled = false; } }; return stop; }
function watcherCard(watch, entries) { const node = document.createElement("article"), header = document.createElement("header"), title = document.createElement("h2"), meta = document.createElement("p"), edit = document.createElement("button"), groupsByDate = new Map(); node.className = "watcher-card"; header.className = "watcher-header"; title.textContent = watch.name; meta.className = "watcher-meta"; meta.textContent = `${watch.theatreName} · #${watch.theatreId}`; edit.className = "edit"; edit.type = "button"; edit.textContent = "Edit"; edit.onclick = () => openForm(watch); header.append(title, meta, edit); node.append(header); entries.forEach((entry) => { const label = date(entry.showtime.startsAt || entry.showtime.showDate); if (!groupsByDate.has(label)) groupsByDate.set(label, []); groupsByDate.get(label).push(entry); }); for (const [label, dayEntries] of groupsByDate) { const day = document.createElement("section"), heading = document.createElement("h3"), chips = document.createElement("div"), seats = dayEntries.reduce((count, entry) => count + availableCount(entry), 0); day.className = "watcher-day"; heading.className = "watcher-day-heading"; heading.textContent = `${label} · ${seats} 🪑 · 🎬 ${dayEntries.length}`; chips.className = "showtime-chips"; dayEntries.forEach((entry) => { const chip = document.createElement("div"), link = document.createElement("a"), failed = entry.check.lastCheckStatus === "failed"; chip.className = "showtime-chip"; link.href = preview(watch.theatreId, entry.id); link.target = "_blank"; link.rel = "noreferrer"; link.textContent = `${failed ? "❌" : "🎬"} #${entry.id} · ${entry.showtime.displayTime || "Time unavailable"} · ${failed ? "Failed" : `${availableCount(entry)} 🪑`}`; chip.append(link, stopShowtimeButton(entry)); chips.append(chip); }); day.append(heading, chips); node.append(day); } return node; }
function stoppedCard(watch) { const showtimes = Object.entries(watch.showtimes || {}), first = showtimes[0], node = document.createElement("article"), top = document.createElement("div"), title = document.createElement(first ? "a" : "span"), status = document.createElement("span"), meta = document.createElement("p"), bottom = document.createElement("div"), hint = document.createElement("span"), edit = document.createElement("button"); node.className = "showtime-card stopped-card"; top.className = "card-top"; title.className = "showtime-link"; title.textContent = `⏸ ${watch.name}`; if (first) { title.href = preview(watch.theatreId, first[0]); title.target = "_blank"; title.rel = "noreferrer"; } status.className = "status stopped"; status.textContent = "Stopped"; top.append(title, status); meta.className = "showtime-meta"; meta.textContent = `${watch.theatreName} · #${watch.theatreId} · ${showtimes.length} ${showtimes.length === 1 ? "showtime" : "showtimes"}`; bottom.className = "card-bottom"; hint.className = "hint"; hint.textContent = "Edit to update and restart"; edit.className = "edit"; edit.type = "button"; edit.textContent = "Edit"; edit.onclick = () => openForm(watch); bottom.append(hint, edit); node.append(top, meta, bottom); return node; }
function inactiveWatches(entries = items()) { const activeWatchIds = new Set(entries.map((entry) => entry.watch.id)); return Object.values(watches).filter((watch) => !activeWatchIds.has(watch.id)); }
function render() { groups.replaceChildren(); const entries = items(), stopped = inactiveWatches(entries), activeWatchIds = new Set(entries.map((entry) => entry.watch.id)); if (!entries.length && !stopped.length) { groups.textContent = "No seat watches yet. Add one to begin."; return; } Object.values(watches).filter((watch) => activeWatchIds.has(watch.id)).sort((left, right) => left.name.localeCompare(right.name)).forEach((watch) => groups.append(watcherCard(watch, entries.filter((entry) => entry.watch.id === watch.id)))); if (stopped.length) { const section = document.createElement("section"), heading = document.createElement("h2"), grid = document.createElement("div"); section.className = "stopped-section"; heading.className = "date-heading"; heading.textContent = `Stopped watches · ${stopped.length}`; grid.className = "stopped-grid"; stopped.sort((left, right) => left.name.localeCompare(right.name)).forEach((watch) => grid.append(stoppedCard(watch))); section.append(heading, grid); groups.append(section); } }
function applySavedWatches(saved) { watches = saved.watches || {}; state = saved.state || {}; const entries = items(), stopped = inactiveWatches(entries), activeWatches = new Set(entries.map((entry) => entry.watch.id)).size; render(); const active = entries.length; loadStatus.textContent = `${activeWatches} active ${activeWatches === 1 ? "watch" : "watches"} · ${active} ${active === 1 ? "showtime" : "showtimes"}${stopped.length ? ` · ${stopped.length} stopped ${stopped.length === 1 ? "watch" : "watches"}` : ""}.`; }
function hasSavedWatch(saved, watchId, payload) { return Object.values(saved.watches || {}).some((watch) => (!watchId || watch.id === watchId) && watch.enabled && watch.name === payload.name && watch.theatreId === payload.theatreId && watch.theatreName === payload.theatreName && Object.keys(watch.showtimes || {}).length === payload.showtimes.length && payload.showtimes.every(({ id }) => watch.showtimes?.[id]?.enabled) && ruleText(watch.rule) === ruleText(payload.rule)); }
async function waitForSavedWatch(watchId, payload) { for (let attempt = 0; attempt < 12; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 2500)); try { const saved = await request("/api/seat-watches", "GET"); applySavedWatches(saved); if (hasSavedWatch(saved, watchId, payload)) { actionResult.textContent = `✅ Saved ${payload.name}.`; return; } } catch (error) { actionResult.textContent = `Still saving ${payload.name}…`; } } actionResult.textContent = `Still saving ${payload.name}. Refresh shortly.`; }
async function load() { loadStatus.textContent = "Loading seat watches…"; try { applySavedWatches(await request("/api/seat-watches", "GET")); } catch (error) { loadStatus.textContent = error.message; } }
document.querySelector("#open-add").onclick = () => openForm();
document.querySelector("#close-dialog").onclick = document.querySelector("#cancel-dialog").onclick = () => dialog.close();
form.onsubmit = async (event) => { event.preventDefault(); const value = new FormData(form), ids = [...new Set(String(value.get("showtimeIds")).split(",").map((id) => id.trim()).filter(Boolean))], watchId = editingWatchId; try { const payload = { name: String(value.get("name")).trim(), theatreId: String(value.get("theatreId")).trim(), theatreName: String(value.get("theatreName")).trim(), showtimes: ids.map((id) => ({ id })), rule: parseRule(String(value.get("rule"))) }; if (!payload.name || !payload.theatreId || !payload.theatreName || !ids.length) throw new Error("Complete every field and provide at least one showtime ID."); await request(watchId ? `/api/seat-watches/${encodeURIComponent(watchId)}` : "/api/seat-watches", watchId ? "PATCH" : "POST", payload); actionResult.textContent = `Saving ${payload.name}…`; dialog.close(); waitForSavedWatch(watchId, payload); } catch (error) { formResult.textContent = error.message; } };
if (!token()) login(); else request("/api/verify", "POST", {}).then(() => { app.hidden = false; return load(); }).catch(login);
