const WORKER = "https://cplex-watcher.cplexwatcher.workers.dev";
const TOKEN_KEY = "UI_ACCESS_TOKEN";
const app = document.querySelector("#app"), groups = document.querySelector("#date-groups"), loadStatus = document.querySelector("#load-status"), actionResult = document.querySelector("#action-result"), dialog = document.querySelector("#watch-dialog"), form = document.querySelector("#watch-form"), formResult = document.querySelector("#form-result");
const DEFAULT_RULE = "E9-E17, F14-F23, G14-G23, H14-H23, I14-I23";
let watches = {}, state = {}, editingWatchId = "";
const token = () => localStorage.getItem(TOKEN_KEY) || "";
const preview = (theatreId, showtimeId) => `https://www.cineplex.com/ticketing/preview?theatreId=${encodeURIComponent(theatreId)}&showtimeId=${encodeURIComponent(showtimeId)}`;
function nextCheck() { const now = new Date(), next = new Date(now); next.setUTCSeconds(0, 0); next.setUTCMinutes(now.getUTCMinutes() < 30 ? 30 : 60); return Math.max(1, Math.ceil((next - now) / 60_000)); }
function login() { window.location.replace("./login.html"); }
async function request(path, method, body) { const response = await fetch(`${WORKER}${path}`, { method, headers: { "content-type": "application/json", authorization: `Bearer ${token()}` }, body: body ? JSON.stringify(body) : undefined }); const value = await response.json(); if (!response.ok) { if (response.status === 401) { localStorage.removeItem(TOKEN_KEY); login(); } throw new Error(value.error || "Request failed."); } return value; }
function parseRule(value) { const rule = {}; for (const range of value.split(",")) { const match = /^\s*([a-z]+)(\d+)\s*-\s*([a-z]+)(\d+)\s*$/i.exec(range); if (!match || match[1].toUpperCase() !== match[3].toUpperCase()) throw new Error("Seat labels must look like E9-E17."); const start = Number(match[2]), end = Number(match[4]); if (!start || start > end) throw new Error("Seat ranges must be positive and ascending."); (rule[match[1].toUpperCase()] ||= []).push([start, end]); } if (!Object.keys(rule).length) throw new Error("Provide at least one seat range."); return rule; }
function ruleText(rule) { return Object.entries(rule || {}).flatMap(([row, ranges]) => ranges.map(([start, end]) => `${row}${start}-${row}${end}`)).join(", "); }
function date(value) { const parsed = new Date(value); return Number.isNaN(parsed) ? "Unknown date" : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", weekday: "long", month: "short", day: "numeric" }).format(parsed); }
function items() { return Object.values(watches).filter((watch) => watch.enabled).flatMap((watch) => Object.entries(watch.showtimes || {}).filter(([, showtime]) => showtime.enabled).map(([id, showtime]) => ({ watch, id, showtime, check: state[watch.id]?.showtimes?.[id] || {} }))).sort((a, b) => String(a.showtime.startsAt || "").localeCompare(String(b.showtime.startsAt || ""))); }
function openForm(watch = null) { editingWatchId = watch?.id || ""; form.reset(); formResult.textContent = ""; document.querySelector("#watch-dialog-title").textContent = watch ? `Edit ${watch.name}` : "Add seat watcher"; document.querySelector("#watch-dialog-hint").textContent = watch ? "Saving rechecks every showtime and starts a fresh seat scan." : "Use a name and showtime IDs. Date and time are found automatically."; document.querySelector("#save-watch").textContent = watch ? "Save changes" : "Start watching"; document.querySelector("#watch-name").value = watch?.name || ""; document.querySelector("#theatre-id").value = watch?.theatreId || ""; document.querySelector("#theatre-name").value = watch?.theatreName || ""; document.querySelector("#showtime-ids").value = watch ? Object.keys(watch.showtimes || {}).join(", ") : ""; document.querySelector("#seat-rule").value = watch ? ruleText(watch.rule) : DEFAULT_RULE; dialog.showModal(); }
function card(item) { const available = Object.values(item.check.selectedSeats || {}).filter((seat) => seat.status === "Available").map((seat) => seat.label).sort(); const failed = item.check.lastCheckStatus === "failed"; const node = document.createElement("article"); node.className = "showtime-card"; const top = document.createElement("div"); top.className = "card-top"; const link = document.createElement("a"); link.className = "showtime-link"; link.href = preview(item.watch.theatreId, item.id); link.target = "_blank"; link.rel = "noreferrer"; link.textContent = `${failed ? "❌" : "⏳"} ${item.watch.name} · ${item.showtime.displayTime || "Time unavailable"}`; const status = document.createElement("span"); status.className = `status${failed ? " error" : ""}`; status.textContent = failed ? "Failed" : `${available.length} seats`; top.append(link, status); const meta = document.createElement("p"); meta.className = "showtime-meta"; meta.textContent = `${item.watch.theatreName} · #${item.watch.theatreId} · #${item.id}`; const bottom = document.createElement("div"); bottom.className = "card-bottom"; const hint = document.createElement("span"); hint.className = "hint"; hint.textContent = failed ? "Retry next run" : (available.join(", ") || `Next check in ${nextCheck()} min`); const actions = document.createElement("div"); actions.className = "card-actions"; const edit = document.createElement("button"); edit.className = "edit"; edit.type = "button"; edit.textContent = "Edit"; edit.onclick = () => openForm(item.watch); const stop = document.createElement("button"); stop.className = "stop"; stop.type = "button"; stop.textContent = "Stop"; stop.onclick = async () => { if (!confirm(`Stop #${item.id} for ${item.watch.name}?`)) return; stop.disabled = true; try { await request(`/api/seat-watches/${encodeURIComponent(item.watch.id)}/showtimes/${item.id}`, "DELETE"); actionResult.textContent = "Stop request queued. Refresh shortly."; } catch (error) { actionResult.textContent = error.message; stop.disabled = false; } }; actions.append(edit, stop); bottom.append(hint, actions); node.append(top, meta, bottom); return node; }
function render() { groups.replaceChildren(); const entries = items(); if (!entries.length) { groups.textContent = "No enabled seat watches. Add one to begin."; return; } const grouped = new Map(); entries.forEach((entry) => { const key = date(entry.showtime.startsAt || entry.showtime.showDate); if (!grouped.has(key)) grouped.set(key, []); grouped.get(key).push(entry); }); for (const [label, values] of grouped) { const section = document.createElement("section"), heading = document.createElement("h2"), grid = document.createElement("div"); section.className = "date-group"; heading.className = "date-heading"; heading.textContent = `${label} · ${values.length} ${values.length === 1 ? "showtime" : "showtimes"}`; grid.className = "showtime-grid"; values.forEach((entry) => grid.append(card(entry))); section.append(heading, grid); groups.append(section); } }
async function load() { loadStatus.textContent = "Loading seat watches…"; try { const saved = await request("/api/seat-watches", "GET"); watches = saved.watches || {}; state = saved.state || {}; render(); loadStatus.textContent = `${items().length} active ${items().length === 1 ? "showtime" : "showtimes"}.`; } catch (error) { loadStatus.textContent = error.message; } }
document.querySelector("#open-add").onclick = () => openForm();
document.querySelector("#close-dialog").onclick = document.querySelector("#cancel-dialog").onclick = () => dialog.close();
form.onsubmit = async (event) => { event.preventDefault(); const value = new FormData(form), ids = [...new Set(String(value.get("showtimeIds")).split(",").map((id) => id.trim()).filter(Boolean))]; try { const payload = { name: String(value.get("name")).trim(), theatreId: String(value.get("theatreId")).trim(), theatreName: String(value.get("theatreName")).trim(), showtimes: ids.map((id) => ({ id })), rule: parseRule(String(value.get("rule"))) }; if (!payload.name || !payload.theatreId || !payload.theatreName || !ids.length) throw new Error("Complete every field and provide at least one showtime ID."); const result = await request(editingWatchId ? `/api/seat-watches/${encodeURIComponent(editingWatchId)}` : "/api/seat-watches", editingWatchId ? "PATCH" : "POST", payload); actionResult.textContent = result.message; dialog.close(); } catch (error) { formResult.textContent = error.message; } };
if (!token()) login(); else request("/api/verify", "POST", {}).then(() => { app.hidden = false; return load(); }).catch(login);
