const WORKER = "https://cplex-watcher.cplexwatcher.workers.dev";
const TOKEN_KEY = "UI_ACCESS_TOKEN";
const app = document.querySelector("#app"), groups = document.querySelector("#date-groups"), loadStatus = document.querySelector("#load-status"), actionResult = document.querySelector("#action-result"), dialog = document.querySelector("#watch-dialog"), form = document.querySelector("#watch-form"), formResult = document.querySelector("#form-result"), layoutDialog = document.querySelector("#seat-preview-dialog"), layoutTitle = document.querySelector("#seat-preview-title"), layoutMeta = document.querySelector("#seat-preview-meta"), layoutSelect = document.querySelector("#seat-preview-showtime"), seatMap = document.querySelector("#seat-map"), layoutResult = document.querySelector("#seat-preview-result"), dashboardPanel = document.querySelector("#dashboard-panel"), seatPanel = document.querySelector("#seat-panel"), ticketPanel = document.querySelector("#ticket-panel"), guidePanel = document.querySelector("#guide-panel"), dashboardTab = document.querySelector("#dashboard-tab"), seatTab = document.querySelector("#seat-tab"), ticketTab = document.querySelector("#ticket-tab"), guideTab = document.querySelector("#guide-tab"), dashboardUpdated = document.querySelector("#dashboard-updated"), dashboardHealth = document.querySelector("#dashboard-health"), dashboardActivity = document.querySelector("#dashboard-activity"), ticketLoadStatus = document.querySelector("#ticket-load-status"), ticketActionResult = document.querySelector("#ticket-action-result"), ticketWatches = document.querySelector("#ticket-watches"), ticketDialog = document.querySelector("#ticket-dialog"), ticketForm = document.querySelector("#ticket-form"), ticketFormResult = document.querySelector("#ticket-form-result");
const DEFAULT_RULE = "E9-E17, F14-F23, G14-G23, H14-H23, I14-I23";
let watches = {}, state = {}, editingWatchId = "", ticketMovies = [], ticketState = {}, ticketSalesStarted = [], ticketLoaded = false;
const token = () => localStorage.getItem(TOKEN_KEY) || "";
const preview = (theatreId, showtimeId) => `https://www.cineplex.com/ticketing/preview?theatreId=${encodeURIComponent(theatreId)}&showtimeId=${encodeURIComponent(showtimeId)}`;
function nextCheck() { const now = new Date(), next = new Date(now); next.setUTCSeconds(0, 0); next.setUTCMinutes(now.getUTCMinutes() < 30 ? 30 : 60); return Math.max(1, Math.ceil((next - now) / 60_000)); }
function login() { window.location.replace("./login.html"); }
async function request(path, method, body) { const response = await fetch(`${WORKER}${path}`, { method, headers: { "content-type": "application/json", authorization: `Bearer ${token()}` }, body: body ? JSON.stringify(body) : undefined }); const value = await response.json(); if (!response.ok) { if (response.status === 401) { localStorage.removeItem(TOKEN_KEY); login(); } throw new Error(value.error || "Request failed."); } return value; }
function parseRule(value) { const rule = {}; for (const range of value.split(",")) { const match = /^\s*([a-z]+)(\d+)\s*-\s*([a-z]+)(\d+)\s*$/i.exec(range); if (!match || match[1].toUpperCase() !== match[3].toUpperCase()) throw new Error("Seat labels must look like E9-E17."); const start = Number(match[2]), end = Number(match[4]); if (!start || start > end) throw new Error("Seat ranges must be positive and ascending."); (rule[match[1].toUpperCase()] ||= []).push([start, end]); } if (!Object.keys(rule).length) throw new Error("Provide at least one seat range."); return rule; }
function ruleText(rule) { return Object.entries(rule || {}).flatMap(([row, ranges]) => ranges.map(([start, end]) => `${row}${start}-${row}${end}`)).join(", "); }
function date(value) { const parsed = new Date(value); return Number.isNaN(parsed) ? "Unknown date" : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", weekday: "long", month: "short", day: "numeric" }).format(parsed); }
function items() { return Object.values(watches).filter((watch) => watch.enabled).flatMap((watch) => Object.entries(watch.showtimes || {}).filter(([, showtime]) => showtime.enabled).map(([id, showtime]) => ({ watch, id, showtime, check: state[watch.id]?.showtimes?.[id] || {} }))).sort((a, b) => String(a.showtime.startsAt || "").localeCompare(String(b.showtime.startsAt || ""))); }
function openForm(watch = null) { editingWatchId = watch?.id || ""; form.reset(); formResult.textContent = ""; document.querySelector("#watch-dialog-title").textContent = watch ? `Edit ${watch.name}` : "Add seat watcher"; document.querySelector("#watch-dialog-hint").textContent = watch ? "Saving rechecks every showtime and starts a fresh seat scan." : "Use a name and showtime IDs. Date and time are found automatically."; document.querySelector("#save-watch").textContent = watch ? "Save changes" : "Start watching"; document.querySelector("#watch-name").value = watch?.name || ""; document.querySelector("#theatre-id").value = watch?.theatreId || ""; document.querySelector("#theatre-name").value = watch?.theatreName || ""; document.querySelector("#showtime-ids").value = watch ? Object.keys(watch.showtimes || {}).join(", ") : ""; document.querySelector("#seat-rule").value = watch ? ruleText(watch.rule) : DEFAULT_RULE; dialog.showModal(); }
function availableCount(item) { return Object.values(item.check.selectedSeats || {}).filter((seat) => seat.status === "Available").length; }
function watchedLabel(label, rule) { const match = /^([A-Z]+)(\d+)$/.exec(label || ""); return Boolean(match && (rule[match[1]] || []).some(([start, end]) => Number(match[2]) >= start && Number(match[2]) <= end)); }
function layoutRowLabel(row) { return (row.seats || []).map((seat) => /^([A-Z])/.exec(seat.label || "")?.[1]).find(Boolean) || "—"; }
function layoutRows(layout) { return [...(layout.standardSeats?.rows || []), ...(layout.dboxSeats?.rows || []), ...(layout.balconySeats?.rows || [])]; }
function renderSeatLayout(watch, layout) { const rows = layoutRows(layout), seats = rows.flatMap((row) => row.seats || []), watched = seats.filter((seat) => watchedLabel(seat.label, watch.rule)).length, columns = layout.totalColumns || Math.max(1, ...seats.map((seat) => Number(seat.columnPhysicalNumber) || 0)); seatMap.replaceChildren(); seatMap.style.setProperty("--seat-columns", columns); for (const row of rows) { const line = document.createElement("div"), label = document.createElement("span"); line.className = "seat-map-row"; label.className = "row-label"; label.textContent = layoutRowLabel(row); line.append(label); if (!(row.seats || []).length) { const aisle = document.createElement("span"); aisle.className = "aisle"; aisle.textContent = "Aisle"; line.append(aisle); } for (const seatData of row.seats || []) { const seat = document.createElement("span"), isWatched = watchedLabel(seatData.label, watch.rule); seat.className = `seat ${isWatched ? "watched" : "unwatched"}`; seat.style.gridColumn = String(Number(seatData.columnPhysicalNumber) + 1); seat.textContent = seatData.label; seat.title = `${seatData.label} · ${isWatched ? "Watched" : "Not watched"} · ${seatData.type || "Seat"}`; line.append(seat); } seatMap.append(line); } layoutMeta.textContent = `${watch.theatreName} · #${watch.theatreId} · ${watched} watched of ${seats.length} Cineplex seats`; layoutResult.textContent = `${watched} watched seats are yellow. Blue seats are visible for context and are not scanned or alerted.`; }
async function loadSeatLayout(watch, showtimeId) { seatMap.replaceChildren(); layoutResult.textContent = "Loading Cineplex seat layout…"; layoutMeta.textContent = `${watch.theatreName} · #${watch.theatreId}`; try { const result = await request(`/api/seat-watches/${encodeURIComponent(watch.id)}/showtimes/${showtimeId}/layout`, "GET"); renderSeatLayout(watch, result.layout); } catch (error) { layoutResult.textContent = error.message; } }
function openSeatPreview(watch, entries) { layoutTitle.textContent = `👁️ Watched seats · ${watch.name}`; layoutSelect.replaceChildren(...entries.map((entry) => { const option = document.createElement("option"); option.value = entry.id; option.textContent = `#${entry.id} · ${entry.showtime.displayTime || "Time unavailable"}`; return option; })); layoutSelect.onchange = () => loadSeatLayout(watch, layoutSelect.value); layoutDialog.showModal(); loadSeatLayout(watch, layoutSelect.value); }
function showtimeTime(showtime) { const displayTime = String(showtime.displayTime || ""); return displayTime.includes(", ") ? displayTime.split(", ").at(-1) : displayTime || "Time unavailable"; }
function iconButton(icon, label, className = "") { const button = document.createElement("button"); button.className = `icon-button ${className}`.trim(); button.type = "button"; button.textContent = icon; button.setAttribute("aria-label", label); button.title = label; return button; }
function collapseButton(target, label) { const button = iconButton("🔺", `Collapse ${label}`, "collapse"); button.setAttribute("aria-expanded", "true"); button.onclick = () => { const collapsed = target.classList.toggle("is-collapsed"); button.textContent = collapsed ? "🔻" : "🔺"; button.setAttribute("aria-label", `${collapsed ? "Expand" : "Collapse"} ${label}`); button.title = button.getAttribute("aria-label"); button.setAttribute("aria-expanded", String(!collapsed)); }; return button; }
function stopShowtimeButton(item) { const stop = iconButton("⏹", `Stop #${item.id} for ${item.watch.name}`, "stop"); stop.onclick = async () => { if (!confirm(`Stop #${item.id} for ${item.watch.name}?`)) return; stop.disabled = true; try { await request(`/api/seat-watches/${encodeURIComponent(item.watch.id)}/showtimes/${item.id}`, "DELETE"); actionResult.textContent = "Stop request queued. Refresh shortly."; } catch (error) { actionResult.textContent = error.message; stop.disabled = false; } }; return stop; }
function deleteWatchButton(watch) { const remove = iconButton("🗑️", `Delete ${watch.name}`, "delete"); remove.onclick = async () => { if (!confirm(`Delete ${watch.name} and every watched showtime? This cannot be undone.`)) return; remove.disabled = true; try { await request(`/api/seat-watches/${encodeURIComponent(watch.id)}`, "DELETE"); actionResult.textContent = `Deleting ${watch.name}…`; } catch (error) { actionResult.textContent = error.message; remove.disabled = false; } }; return remove; }
function actionMenu(watch, entries = []) { const menu = document.createElement("details"), trigger = document.createElement("summary"), list = document.createElement("div"); menu.className = "action-menu"; trigger.className = "icon-button action-menu-trigger"; trigger.textContent = "⋯"; trigger.setAttribute("aria-label", `Actions for ${watch.name}`); trigger.title = `Actions for ${watch.name}`; list.className = "action-menu-list"; if (entries.length) { const seatPreview = iconButton("🗺️", `Preview watched seats for ${watch.name}`, "action-menu-item"); seatPreview.append(" Preview seats"); seatPreview.onclick = () => { menu.open = false; openSeatPreview(watch, entries); }; list.append(seatPreview); } const edit = iconButton("✏️", `Edit ${watch.name}`, "action-menu-item"); edit.append(" Edit"); edit.onclick = () => { menu.open = false; openForm(watch); }; const remove = deleteWatchButton(watch); remove.classList.add("action-menu-item"); remove.append(" Delete"); list.append(edit, remove); menu.append(trigger, list); return menu; }
function watcherCard(watch, entries) { const node = document.createElement("article"), header = document.createElement("header"), title = document.createElement("h2"), meta = document.createElement("p"), theatre = document.createElement("span"), groupsByDate = new Map(), seats = entries.reduce((count, entry) => count + availableCount(entry), 0); node.className = "watcher-card"; header.className = "watcher-header"; title.textContent = watch.name; meta.className = "watcher-meta"; theatre.className = "theatre-name"; theatre.textContent = watch.theatreName; theatre.title = `🎥 #${watch.theatreId}`; meta.append(theatre, ` · ${seats} 🪑 · ${entries.length} 🎬`); header.append(title, meta, actionMenu(watch, entries), collapseButton(node, watch.name)); node.append(header); entries.forEach((entry) => { const label = date(entry.showtime.startsAt || entry.showtime.showDate); if (!groupsByDate.has(label)) groupsByDate.set(label, []); groupsByDate.get(label).push(entry); }); for (const [label, dayEntries] of groupsByDate) { const day = document.createElement("section"), dayHeader = document.createElement("div"), heading = document.createElement("h3"), chips = document.createElement("div"), daySeats = dayEntries.reduce((count, entry) => count + availableCount(entry), 0); day.className = "watcher-day"; dayHeader.className = "watcher-day-header"; heading.className = "watcher-day-heading"; heading.textContent = `${label} · ${daySeats} 🪑`; chips.className = "showtime-chips"; dayEntries.forEach((entry) => { const chip = document.createElement("div"), link = document.createElement("a"), failed = entry.check.lastCheckStatus === "failed"; chip.className = "showtime-chip"; link.href = preview(watch.theatreId, entry.id); link.target = "_blank"; link.rel = "noreferrer"; link.textContent = `#${entry.id} · ${showtimeTime(entry.showtime)} · ${failed ? "❌ Failed" : `${availableCount(entry)} 🪑`}`; chip.append(link, stopShowtimeButton(entry)); chips.append(chip); }); dayHeader.append(heading, collapseButton(day, label)); day.append(dayHeader, chips); node.append(day); } return node; }
function stoppedCard(watch) { const showtimes = Object.entries(watch.showtimes || {}), first = showtimes[0], node = document.createElement("article"), top = document.createElement("div"), title = document.createElement(first ? "a" : "span"), status = document.createElement("span"), meta = document.createElement("p"), bottom = document.createElement("div"), hint = document.createElement("span"); node.className = "showtime-card stopped-card"; top.className = "card-top"; title.textContent = `⏸ ${watch.name}`; if (first) { title.href = preview(watch.theatreId, first[0]); title.target = "_blank"; title.rel = "noreferrer"; } status.className = "status stopped"; status.textContent = "Stopped"; top.append(title, status); meta.className = "showtime-meta"; meta.textContent = `${watch.theatreName} · #${watch.theatreId} · ${showtimes.length} ${showtimes.length === 1 ? "showtime" : "showtimes"}`; bottom.className = "card-bottom"; hint.className = "hint"; hint.textContent = "Edit to update and restart"; bottom.append(hint, actionMenu(watch)); node.append(top, meta, bottom); return node; }
function inactiveWatches(entries = items()) { const activeWatchIds = new Set(entries.map((entry) => entry.watch.id)); return Object.values(watches).filter((watch) => !activeWatchIds.has(watch.id)); }
function render() { groups.replaceChildren(); const entries = items(), stopped = inactiveWatches(entries), activeWatchIds = new Set(entries.map((entry) => entry.watch.id)); if (!entries.length && !stopped.length) { groups.textContent = "No seat watches yet. Add one to begin."; return; } Object.values(watches).filter((watch) => activeWatchIds.has(watch.id)).sort((left, right) => left.name.localeCompare(right.name)).forEach((watch) => groups.append(watcherCard(watch, entries.filter((entry) => entry.watch.id === watch.id)))); if (stopped.length) { const section = document.createElement("section"), heading = document.createElement("h2"), grid = document.createElement("div"); section.className = "stopped-section"; heading.className = "date-heading"; heading.textContent = `Stopped watches · ${stopped.length}`; grid.className = "stopped-grid"; stopped.sort((left, right) => left.name.localeCompare(right.name)).forEach((watch) => grid.append(stoppedCard(watch))); section.append(heading, grid); groups.append(section); } }
function applySavedWatches(saved) { watches = saved.watches || {}; state = saved.state || {}; const entries = items(), stopped = inactiveWatches(entries), activeWatches = new Set(entries.map((entry) => entry.watch.id)).size; render(); const active = entries.length; loadStatus.textContent = `${activeWatches} active ${activeWatches === 1 ? "watch" : "watches"} · ${active} ${active === 1 ? "showtime" : "showtimes"}${stopped.length ? ` · ${stopped.length} stopped ${stopped.length === 1 ? "watch" : "watches"}` : ""}.`; renderDashboard(); }
function hasSavedWatch(saved, watchId, payload) { return Object.values(saved.watches || {}).some((watch) => (!watchId || watch.id === watchId) && watch.enabled && watch.name === payload.name && watch.theatreId === payload.theatreId && watch.theatreName === payload.theatreName && Object.keys(watch.showtimes || {}).length === payload.showtimes.length && payload.showtimes.every(({ id }) => watch.showtimes?.[id]?.enabled) && ruleText(watch.rule) === ruleText(payload.rule)); }
async function waitForSavedWatch(watchId, payload) { for (let attempt = 0; attempt < 12; attempt += 1) { await new Promise((resolve) => setTimeout(resolve, 2500)); try { const saved = await request("/api/seat-watches", "GET"); applySavedWatches(saved); if (hasSavedWatch(saved, watchId, payload)) { actionResult.textContent = `✅ Saved ${payload.name}.`; return; } } catch (error) { actionResult.textContent = `Still saving ${payload.name}…`; } } actionResult.textContent = `Still saving ${payload.name}. Refresh shortly.`; }
async function load() { loadStatus.textContent = "Loading seat watches…"; try { applySavedWatches(await request("/api/seat-watches", "GET")); } catch (error) { loadStatus.textContent = error.message; } }
const REPOSITORY_RAW_URL = "https://raw.githubusercontent.com/ettersAy/cplex-watcher/main";
function movieKey(url) { try { return new URL(url).pathname.replace(/\/$/, "").split("/").at(-1); } catch { return ""; } }
function ticketTime(value) { const normalized = String(value || "").replace(/(\.\d{3})\d+/, "$1").replace("+00:00", "Z"), parsed = new Date(normalized); return Number.isNaN(parsed.getTime()) ? "Not checked yet" : new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", dateStyle: "medium", timeStyle: "short" }).format(parsed); }
async function repositoryFile(path) { const response = await fetch(`${REPOSITORY_RAW_URL}/${path}?v=${Date.now()}`, { cache: "no-store" }); if (!response.ok) throw new Error(`Could not load ${path}: HTTP ${response.status}.`); return response.json(); }
function timestamp(value) { const normalized = String(value || "").replace(/(\.\d{3})\d+/, "$1").replace("+00:00", "Z"), parsed = new Date(normalized); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function latestCheck(checks) { return checks.filter((check) => timestamp(check?.lastCheckedAt)).sort((left, right) => timestamp(right.lastCheckedAt) - timestamp(left.lastCheckedAt))[0] || null; }
function minutesUntil(interval) { const now = new Date(), next = new Date(now); next.setSeconds(0, 0); next.setMinutes(Math.ceil((next.getMinutes() + 1) / interval) * interval); return Math.max(1, Math.ceil((next - now) / 60_000)); }
function dashboardStat(value, label) { const node = document.createElement("div"), number = document.createElement("strong"), description = document.createElement("span"); node.className = "dashboard-stat"; number.textContent = String(value); description.textContent = label; node.append(number, description); return node; }
function healthCard(name, healthy, stats, nextMinutes, last) { const card = document.createElement("article"), top = document.createElement("div"), title = document.createElement("span"), status = document.createElement("span"), statGrid = document.createElement("div"), timing = document.createElement("div"), next = document.createElement("b"), checked = document.createElement("span"); card.className = "health-card"; top.className = "health-card-top"; title.className = "health-name"; title.textContent = name; status.className = `health-state${healthy ? "" : " error"}`; status.textContent = healthy ? "🟢 Healthy" : "🔴 Needs attention"; top.append(title, status); statGrid.className = "dashboard-stats"; stats.forEach(([value, label]) => statGrid.append(dashboardStat(value, label))); timing.className = "scan-timing"; next.textContent = `👁️ Next scan in ${nextMinutes} min`; checked.className = "hint"; checked.textContent = `🕒 Last scan: ${last ? ticketTime(last.lastCheckedAt) : "Not checked yet"}`; timing.append(next, checked); card.append(top, statGrid, timing); return card; }
function renderDashboard() { const seatEntries = items(), seatChecks = seatEntries.map((entry) => entry.check), latestSeat = latestCheck(seatChecks), seatFailures = seatChecks.filter((check) => check.lastCheckStatus === "failed").length, activeSeatWatches = new Set(seatEntries.map((entry) => entry.watch.id)).size, availableSeats = seatEntries.reduce((count, entry) => count + availableCount(entry), 0), ticketChecks = ticketMovies.map((movie) => ticketState[movieKey(movie.url)] || {}), latestTicket = latestCheck(ticketChecks), ticketFailures = ticketChecks.filter((check) => check.lastCheckStatus === "failed" || check.lastError).length;
  dashboardHealth.replaceChildren(healthCard("🎟 Seat watcher", seatFailures === 0, [[activeSeatWatches, "active watchers"], [seatEntries.length, "showtimes watched"], [availableSeats, "seats available"], [seatFailures, "failed checks"]], minutesUntil(5), latestSeat), healthCard("🎫 Ticket watcher", ticketLoaded && ticketFailures === 0, [[ticketMovies.length, "movies watched"], [ticketSalesStarted.length, "sales started"], [ticketFailures, "failed checks"], [ticketLoaded ? "Live" : "…", "data status"]], minutesUntil(30), latestTicket));
  dashboardActivity.replaceChildren(); const activity = [["🎟 Seat watcher", latestSeat, seatFailures ? `${seatFailures} failed check${seatFailures === 1 ? "" : "s"}` : `${availableSeats} matching seats available`], ["🎫 Ticket watcher", latestTicket, ticketLoaded ? `${ticketMovies.length} movies checked · ${ticketSalesStarted.length} sales started` : "Loading ticket-watch data…"]]; activity.forEach(([name, check, result]) => { const item = document.createElement("li"), time = document.createElement("time"); time.textContent = check ? ticketTime(check.lastCheckedAt) : "Not checked yet"; item.append(time, `${name} — ${result}`); dashboardActivity.append(item); }); dashboardUpdated.textContent = `Updated ${new Intl.DateTimeFormat("en-CA", { timeZone: "America/Toronto", timeStyle: "short" }).format(new Date())}`;
}
function ticketCard(movie, salesStarted) { const key = movieKey(movie.url), check = ticketState[key] || {}, failed = !salesStarted && (!check || check.lastCheckStatus === "failed" || check.lastError), started = salesStarted || (!failed && check.hasShowtimes), node = document.createElement("article"), main = document.createElement("div"), link = document.createElement("a"), meta = document.createElement("p"), stub = document.createElement("div"), icon = document.createElement("span"), status = document.createElement("span"), footer = document.createElement("footer"), footerText = document.createElement("span");
  node.className = "ticket-card"; main.className = "ticket-main"; link.className = "ticket-link"; link.href = movie.url; link.target = "_blank"; link.rel = "noreferrer"; link.textContent = movie.name || movie.title || check.name || key || "Cineplex movie"; meta.className = "ticket-meta"; meta.textContent = failed ? `Last check failed · ${ticketTime(check.lastCheckedAt)}` : salesStarted ? `Sales detected ${ticketTime(movie.salesStartedAt)}` : `Checked ${ticketTime(check.lastCheckedAt)}`; main.append(link, meta);
  stub.className = "ticket-stub"; icon.className = "ticket-icon"; status.className = `ticket-status ${started ? "started" : failed ? "failed" : "waiting"}`; icon.textContent = started ? "🎉" : failed ? "⚠️" : "⏳"; status.textContent = started ? "Sales started" : failed ? "Check failed" : "Watching"; stub.append(icon, status);
  footer.className = "ticket-footer"; footerText.className = "hint"; footerText.textContent = started ? "Open Cineplex to buy tickets" : "Watching for sales"; footer.append(footerText);
  if (!started) { const stop = iconButton("⏹", `Stop watching ${link.textContent}`, "stop"); stop.onclick = async () => { if (!confirm(`Stop watching ${link.textContent}?`)) return; stop.disabled = true; try { const result = await request("/api/queue", "DELETE", { url: movie.url }); ticketActionResult.textContent = result.message || "Stop request queued. Refresh shortly."; } catch (error) { ticketActionResult.textContent = error.message; stop.disabled = false; } }; footer.append(stop); }
  node.append(main, stub, footer); return { node, started };
}
function ticketMovieName(movie) { return String(movie.name || movie.title || ticketState[movieKey(movie.url)]?.name || movieKey(movie.url) || ""); }
function renderTicketWatches() { ticketWatches.replaceChildren(); const startedSection = document.createElement("section"), waitingSection = document.createElement("section"), startedHeading = document.createElement("h3"), waitingHeading = document.createElement("h3"), startedGrid = document.createElement("div"), waitingGrid = document.createElement("div"), sortedStarted = [...ticketSalesStarted].sort((left, right) => ticketMovieName(left).localeCompare(ticketMovieName(right))), sortedWaiting = [...ticketMovies].sort((left, right) => ticketMovieName(left).localeCompare(ticketMovieName(right)));
  startedSection.className = waitingSection.className = "ticket-section"; startedHeading.className = waitingHeading.className = "ticket-section-heading"; startedGrid.className = waitingGrid.className = "ticket-grid";
  for (const movie of sortedStarted) startedGrid.append(ticketCard(movie, true).node);
  for (const movie of sortedWaiting) waitingGrid.append(ticketCard(movie, false).node);
  startedHeading.textContent = `🎉 Sales started · ${startedGrid.childElementCount}`; waitingHeading.textContent = `⏳ Still watching · ${waitingGrid.childElementCount}`; startedSection.append(startedHeading, startedGrid); waitingSection.append(waitingHeading, waitingGrid); ticketWatches.append(startedSection, waitingSection);
}
async function loadTicketWatches() { ticketLoadStatus.textContent = "Loading ticket watches…"; try { const [movies, savedState, salesStarted] = await Promise.all([repositoryFile("movies.json"), repositoryFile("state.json"), repositoryFile("sales-started.json")]); ticketMovies = Array.isArray(movies) ? movies : movies.movies || []; ticketState = savedState.movies || savedState || {}; ticketSalesStarted = Array.isArray(salesStarted) ? salesStarted : salesStarted.movies || []; ticketLoaded = true; renderTicketWatches(); ticketLoadStatus.textContent = `${ticketMovies.length} active ${ticketMovies.length === 1 ? "ticket watch" : "ticket watches"}.`; } catch (error) { ticketLoadStatus.textContent = error.message; ticketLoaded = false; } finally { renderDashboard(); } }
function selectTab(name) { const selected = { dashboard: dashboardPanel, seat: seatPanel, ticket: ticketPanel, guide: guidePanel }[name]; if (!selected) return; [dashboardPanel, seatPanel, ticketPanel, guidePanel].forEach((panel) => { panel.hidden = panel !== selected; }); [[dashboardTab, "dashboard"], [seatTab, "seat"], [ticketTab, "ticket"], [guideTab, "guide"]].forEach(([tab, tabName]) => tab.setAttribute("aria-selected", String(tabName === name))); if (name === "ticket" && !ticketLoaded) loadTicketWatches(); }
document.querySelector("#open-add").onclick = () => openForm();
dashboardTab.onclick = () => selectTab("dashboard");
seatTab.onclick = () => selectTab("seat");
ticketTab.onclick = () => selectTab("ticket");
guideTab.onclick = () => selectTab("guide");
document.querySelectorAll("[data-open-tab]").forEach((button) => { button.onclick = () => selectTab(button.dataset.openTab); });
document.querySelector("#refresh-dashboard").onclick = () => { load(); loadTicketWatches(); };
document.querySelectorAll(".copy-command").forEach((button) => { button.onclick = async () => { try { await navigator.clipboard.writeText(button.parentElement.querySelector("code").textContent); button.textContent = "Copied"; setTimeout(() => { button.textContent = "Copy"; }, 1200); } catch { button.textContent = "Unavailable"; setTimeout(() => { button.textContent = "Copy"; }, 1200); } }; });
document.querySelector("#open-ticket-add").onclick = () => { ticketForm.reset(); ticketFormResult.textContent = ""; ticketDialog.showModal(); };
document.querySelector("#close-ticket-dialog").onclick = document.querySelector("#cancel-ticket-dialog").onclick = () => ticketDialog.close();
document.querySelector("#close-dialog").onclick = document.querySelector("#cancel-dialog").onclick = () => dialog.close();
document.querySelector("#close-seat-preview").onclick = () => layoutDialog.close();
form.onsubmit = async (event) => { event.preventDefault(); const value = new FormData(form), ids = [...new Set(String(value.get("showtimeIds")).split(",").map((id) => id.trim()).filter(Boolean))], watchId = editingWatchId; try { const payload = { name: String(value.get("name")).trim(), theatreId: String(value.get("theatreId")).trim(), theatreName: String(value.get("theatreName")).trim(), showtimes: ids.map((id) => ({ id })), rule: parseRule(String(value.get("rule"))) }; if (!payload.name || !payload.theatreId || !payload.theatreName || !ids.length) throw new Error("Complete every field and provide at least one showtime ID."); await request(watchId ? `/api/seat-watches/${encodeURIComponent(watchId)}` : "/api/seat-watches", watchId ? "PATCH" : "POST", payload); actionResult.textContent = `Saving ${payload.name}…`; dialog.close(); waitForSavedWatch(watchId, payload); } catch (error) { formResult.textContent = error.message; } };
ticketForm.onsubmit = async (event) => { event.preventDefault(); const titles = String(new FormData(ticketForm).get("titles") || "").trim(); if (!titles) { ticketFormResult.textContent = "Provide at least one movie name."; return; } try { const result = await request("/api/queue", "POST", { titles }); ticketActionResult.textContent = result.message || "Ticket-watch request queued."; ticketDialog.close(); ticketLoaded = false; } catch (error) { ticketFormResult.textContent = error.message; } };
if (!token()) login(); else request("/api/verify", "POST", {}).then(() => { app.hidden = false; return Promise.all([load(), loadTicketWatches()]); }).catch(login);
